FROM node:20-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG VITE_SUPABASE_URL=""
ARG VITE_SUPABASE_PUBLISHABLE_KEY=""
ARG VITE_SUPABASE_ANON_KEY=""
ARG VITE_SPEC_DEV_FAST_ECONOMY="false"
ARG VITE_SPEC_WHITELIST_BONUS_FLUX="0"
ARG VITE_SPEC_DAILY_CLAIM_FLUX="1"
ARG VITE_SPEC_FAUCET_INTERVAL_SECONDS="86400"
ARG VITE_SPEC_BOX_PRICE_MULTIPLIER="1"
ARG VITE_FEATURE_DEX_TRADING_ENABLED="false"

ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_PUBLISHABLE_KEY=$VITE_SUPABASE_PUBLISHABLE_KEY
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_SPEC_DEV_FAST_ECONOMY=$VITE_SPEC_DEV_FAST_ECONOMY
ENV VITE_SPEC_WHITELIST_BONUS_FLUX=$VITE_SPEC_WHITELIST_BONUS_FLUX
ENV VITE_SPEC_DAILY_CLAIM_FLUX=$VITE_SPEC_DAILY_CLAIM_FLUX
ENV VITE_SPEC_FAUCET_INTERVAL_SECONDS=$VITE_SPEC_FAUCET_INTERVAL_SECONDS
ENV VITE_SPEC_BOX_PRICE_MULTIPLIER=$VITE_SPEC_BOX_PRICE_MULTIPLIER
ENV VITE_FEATURE_DEX_TRADING_ENABLED=$VITE_FEATURE_DEX_TRADING_ENABLED

RUN test -n "$VITE_SUPABASE_URL" || (echo "Missing VITE_SUPABASE_URL at image build time" && exit 1)
RUN test -n "$VITE_SUPABASE_PUBLISHABLE_KEY" || test -n "$VITE_SUPABASE_ANON_KEY" || (echo "Missing VITE_SUPABASE_PUBLISHABLE_KEY or VITE_SUPABASE_ANON_KEY at image build time" && exit 1)

RUN npm run build

FROM nginx:1.27-alpine AS runtime

COPY deploy/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
  CMD wget -q -O /dev/null http://127.0.0.1/ || exit 1

CMD ["nginx", "-g", "daemon off;"]
